BibleBot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^knowledge_base/', include('knowledge_base.urls')),
]

knowledge_base/urls.py
from django.conf.urls import url
from django.template import loader
from . import views
from django.views.generic import TemplateView

app_name = 'knowledge_base'

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),
    url(r'^web/(?P<book_chapter>\w+)/(?P<focused_verses>[\d-]+)/$', views.WEB.as_view(), name='web'),
    url(r'^vent/', views.Vent, name='Vent'),
    # url(r'^load_classifiers/', views.load_classifiers, name='load_classifiers'),
    url(r'^overview$', views.Overview.as_view(), name='overview'),
    url(r'^sentence_labels$', views.SentenceLabels.as_view(), name='SentenceLabels'),
    url(r'^post_labels$', views.PostLabels.as_view(), name='PostLabels'),
    url(r'^anwser_rules$', views.AnswerRules.as_view(), name='AnswerRules'),
    url(r'^sentence_labeling/(?P<pk>[0-9]+)$', views.SentenceLabeling.as_view(), name='SentenceLabeling'),
    url(r'^sentence_registering/$', views.SentenceRegistering, name='SentenceRegistering'),
    url(r'^svm_learn_sentences/', views.svm_learn_sentences, name='svm_learn_sentences'),
    url(r'^svm_learn_posts/', views.svm_learn_posts, name='svm_learn_posts'),
    url(r'^initial_data/', views.initial_data, name='initial_data'),
    url(r'^initial_PostLabel/', views.initial_PostLabel, name='initial_PostLadata'),
    url(r'^initial_SentenceLabel/', views.initial_SentenceLabel, name='initial_SentenceLabel'),
    url(r'^initial_SentenceLabelSynonym/', views.initial_SentenceLabelSynonym, name='initial_SentenceLabelSynonym'),
    url(r'^initial_Sentence/', views.initial_Sentence, name='initial_Sentence'),
    url(r'^initial_Post/', views.initial_Post, name='initial_Post'),
    url(r'^initial_Verse/', views.initial_Verse, name='initial_Verse'),
    url(r'^initial_Emotion/', views.initial_Emotion, name='initial_Emotion'),
    url(r'^initial_EmotionTopicMap/', views.initial_EmotionTopicMap, name='initial_EmotionTopicMap'),
    url(r'^initial_Comment/', views.initial_Comment, name='initial_Comment'),
    url(r'^initial_VerseMap/', views.initial_VerseMap, name='initial_VerseMap'),
    url(r'^posts_into_catgories/', views.posts_into_catgories, name='posts_into_catgories'),
]

knowledge_base/models.py
from django.db import models
from datetime import datetime

# Create your models here.


# yet to add 
#abortion
#physical_disease
#financial
class PostLabel(models.Model):
	title = models.CharField(max_length=100)
	positives = models.IntegerField(default=0)
	precision = models.FloatField(default=-1)
	recall = models.FloatField(default=-1)

	def __str__(self): return u'{}'.format(self.title)
	class Meta:
		ordering = ["title"]		

class Post(models.Model):
	title = models.CharField(max_length=300)
	body = models.TextField()
	url = models.CharField(max_length=400)
	def __str__(self): return u'{}'.format(self.title)

class PostMembership(models.Model):	
	label = models.ForeignKey(PostLabel, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	score = models.FloatField(default=-1)
	date_created = models.DateTimeField(default=datetime.now)
	class Meta:
		ordering = ["label"]			
	def __str__(self): return u"{0} -- {1}".format(self.label, self.post.title)

class SentenceLabel(models.Model):
	title = models.CharField(max_length=100)
	positives = models.IntegerField(default=0)
	supervisors = models.IntegerField(default=0)
	precision = models.FloatField(default=-1)
	recall = models.FloatField(default=-1)
	class Meta:
		ordering = ["title"]	
	def __str__(self): return u'{}'.format(self.title)


class SentenceLabelSynonym(models.Model):
	label = models.ForeignKey(SentenceLabel, on_delete=models.CASCADE)
	synonym = models.CharField(max_length=100)
	class Meta:
		ordering = ["label", "synonym"]	
	def __str__(self): return u'{0} -- {1}'.format(self.label.title, self.synonym)


class Sentence(models.Model):
	sentenceNo = models.IntegerField(default=-1)
	body = models.TextField()
	def __str__(self): return u'{}'.format(self.body)


class SentenceMembership(models.Model):
	label = models.ForeignKey(SentenceLabel, on_delete=models.CASCADE)
	sentence = models.ForeignKey(Sentence, on_delete=models.CASCADE)
	score = models.FloatField(default=-1)
	date_created = models.DateTimeField(default=datetime.now)
	supervise = models.BooleanField(default=False)
	class Meta:
		ordering = ["label"]		
	def __str__(self): return u"{0} -- {1}".format(self.label, self.sentence.body)


class SentenceInPost(models.Model):
	sentence = models.ForeignKey(Sentence, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE)
	def __str__(self): return u"{0} -- {1}".format(self.sentence, self.post.title)


class Verse(models.Model):
	title = models.CharField(max_length=30)
	body = models.TextField()
	url = models.CharField(max_length=60)
	class Meta:
		ordering = ["title"]			
	def __str__(self): return u'{}'.format(self.title)


class Emotion(models.Model):
	title = models.CharField(max_length=40)
	def __str__(self): return u'{}'.format(self.title)


class EmotionTopicMap(models.Model):
	plabel = models.ForeignKey(PostLabel, on_delete=models.CASCADE)
	slabel = models.ForeignKey(SentenceLabel, on_delete=models.CASCADE)
	emotion = models.ForeignKey(Emotion, on_delete=models.CASCADE)
	score = models.FloatField(default=-1)
	class Meta:
		ordering = ["plabel", "slabel"]		
	def __str__(self): return u'{0} -- {1} -- {2} -- {3}'.format(self.plabel.title, self.slabel.title, self.emotion.title, self.score)


class Comment(models.Model):
	introduction = models.CharField(max_length=200)
	postscript = models.CharField(max_length=500, default="")
	class Meta:
		ordering = ["introduction"]	
	def __str__(self): return u'{}'.format(self.introduction)


class VerseTopicMap(models.Model):
	plabel = models.ForeignKey(PostLabel, on_delete=models.CASCADE)
	verse = models.ForeignKey(Verse, on_delete=models.CASCADE)
	comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
	score = models.FloatField(default=-1)
	class Meta:
		ordering = ["plabel", "score"]
	def __str__(self): return u'{0} -- {1} -- {2} -- {3}'.format(self.plabel.title, self.score, self.verse.title, self.comment.introduction)


class VerseEmotionMap(models.Model):
	emotion = models.ForeignKey(Emotion, on_delete=models.CASCADE)
	verse = models.ForeignKey(Verse, on_delete=models.CASCADE)
	comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
	score = models.FloatField(default=-1)
	class Meta:
		ordering = ["emotion", "score"]
	def __str__(self): return u'{0} -- {1} -- {2} -- {3}'.format(self.emotion.title, self.score, self.verse.title, self.comment.introduction)


class Question(models.Model):
	body = models.TextField()	
	def __str__(self): return u'{}'.format(self.body)


class Answer(models.Model):
	title = models.CharField(max_length=20)
	body = models.TextField()	
	def __str__(self): return u'{}'.format(self.title)

# class AnswerRule(models.Model):
	

knowledge_base/views.py
# coding=utf-8

import json
import re
import random
import copy
import time
import uuid
from collections import defaultdict 
import numpy as np
# import pandas as pd
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn import svm
from scw import SCW1
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.multiclass import OneVsRestClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import GridSearchCV
from sklearn. model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.externals import joblib
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import TemplateView, DetailView
from knowledge_base.models import PostLabel, Post, PostMembership, SentenceLabel, SentenceLabelSynonym, Sentence, SentenceMembership, SentenceInPost, Verse, Emotion, EmotionTopicMap, Comment, VerseTopicMap, VerseEmotionMap, Question, Answer
from django.utils.functional import cached_property
from django.shortcuts import redirect
from django.db.models import Q
from django.core.cache import cache
from django.views.decorators.csrf import ensure_csrf_cookie

# class Labels(TemplateView):
# 	template_name='knowledge_base/labels.html'
# 	post_title = 'post labels'
# 	sentence_title = 'sentence labels'

# 	@cached_property
# 	def post_labels(self): return PostLabel.objects.all()	

# 	@cached_property
# 	def sentence_labels(self): return SentenceLabel.objects.all()


class Home(TemplateView):
	template_name='knowledge_base/home.html'
	title = 'BibleBot'

sentences_vectorizer = joblib.load('sentences.vectorizer')
sentences_classfier = joblib.load('svc-sentences.model')
posts_vectorizer= joblib.load('posts.vectorizer')
posts_classfier = joblib.load('svc-posts.model')
@ensure_csrf_cookie
def Vent(request):
	content = request.POST.get('item')
	content = re.split("\.|\n", content)
	# print(content)
	# cache.set('my_key', 'hello, world!', 30)
	# print(cache.get('my_key'))

	sentences = []
	for line in content:
		if re.match(r'^\s*$',line): continue 
		line = line.replace('\n',' ')
		line = line.replace('\r',' ')
		line = line.replace('\t',' ')
		line = line.replace('\\n',' ')
		line = line.replace('\\r',' ')
		line = line.replace('\\t',' ')
		line = line.replace('\\','')
		line = line.replace('^','')
		line = line.replace('\,','')
		line = line.replace('"title": null,','"title": "null",')
		line = line.replace('"body": null,','"body": "null",')
		line = line.replace('"','\\"')
		line = line.replace('\\"title\\": \\"','"title": "')
		line = line.replace('\\", \\"body\\": \\"','", "body": "')
		line = line.replace('\\", \\"url\\": \\"', '", "url": "')
		line = line.replace('\\"}', '"}')
		line = line.replace('\\"', '')
		line = re.sub(r'\s+',' ', line)
		line = re.sub(r'[\$\£\%\^\&\*\-\_\=\+\#\~\@]+','', line)
		line = re.sub(r'[0-9]+','', line)
		line = line.lower()
		line = line.strip()
		sentences.append(line)
		# print(line)

	try:
		post = ' '.join(sentences)
		emotion_adjustment = -0.6
		sentence_class_score = defaultdict(int)
		sentences = sentences_vectorizer.transform(sentences).toarray()
		pred_sentences_dist = sentences_classfier.decision_function(sentences)
		# print(pred_sentences_dist)
		for p in pred_sentences_dist:
			for cid in range(len(p)): 
				score = p[cid] 
				if score > emotion_adjustment: 
					sentence_class = sentences_classfier.classes_[cid]
					if sentence_class != 'NOT_EMOTION':
						sentence_class_score[sentence_class] += (score - emotion_adjustment)
		# print(sentence_class_score)

		post_class_score = defaultdict(int)
		post = posts_vectorizer.transform([post]).toarray()
		pred_posts_dist = posts_classfier.decision_function(post)
		pred_post_dist = pred_posts_dist[0]
		for cid in range(len(pred_post_dist)): 
			score = pred_post_dist[cid] 
			if score > 0: 
				post_class = posts_classfier.classes_[cid]
				post_class_score[post_class] = score
		# print(post_class_score)	

		# ventid = str(uuid.uuid4())
		reply_ordered = makeReply(post_class_score, sentence_class_score)
		# print(reply_ordered)
		return HttpResponse(json.dumps(reply_ordered), content_type='application/json')
	except:
		data = {'status': "notReady"}
		return HttpResponse(json.dumps(data), content_type='application/json')

@ensure_csrf_cookie
def load_classifiers(request):
	global sentences_vectorizer 
	global sentences_classfier 
	global posts_vectorizer 
	global posts_classfier 

	if sentences_vectorizer == None: sentences_vectorizer = joblib.load('sentences.vectorizer')
	if sentences_classfier == None: sentences_classfier = joblib.load('svc-sentences.model')
	if posts_vectorizer == None: posts_vectorizer= joblib.load('posts.vectorizer')
	if posts_classfier == None: posts_classfier = joblib.load('svc-posts.model')

	data = {'message': "classifiers loaded"}
	return HttpResponse(json.dumps(data), content_type='application/json')

def makeReply(post_class_score, sentence_class_score):
	# adjust score of post_class_score, sentence_class_score
	score = 16
	post_class_score_top5 = {}
	for k in reversed(sorted(post_class_score, key=lambda k:post_class_score[k])):
		post_class_score_top5[k] = score
		score = score/2
		if score < 1: break

	score = 16
	for k in reversed(sorted(sentence_class_score, key=lambda k:sentence_class_score[k])):
		sentence_class_score[k] = score
		score = score/2

	emotion_score = {}
	fractal = 0
	for p in post_class_score_top5:
		pInst = PostLabel.objects.get(title=p)
		for s in sentence_class_score:
			sInst = SentenceLabel.objects.get(title=s)
			sub = EmotionTopicMap.objects.filter(plabel=pInst, slabel=sInst).order_by('pk')
			for elem in sub:
				adjust = (1000 + fractal) / 1000
				score = post_class_score_top5[p] * sentence_class_score[s] * elem.score * adjust
				# score = post_class_score_top5[p] * sentence_class_score[s] * elem.score
				emotion_score[elem.emotion] = score
				fractal += 1
	
	# adjust score of emotion_score
	score = 16
	for k in reversed(sorted(emotion_score, key=lambda k:emotion_score[k])):
		emotion_score[k] = score
		score = score/2

	print(post_class_score_top5)
	print(emotion_score)

	reply_score = {}
	reply_content = {}
	fractal = 0
	for plabel in post_class_score_top5:
		pInst = PostLabel.objects.get(title=plabel)
		sub = VerseTopicMap.objects.filter(plabel=pInst).order_by('pk')
		for reply in sub:
			adjust = (1000 + fractal) / 1000
			key = (reply.verse.pk, reply.comment.pk)
			score = post_class_score_top5[plabel] * reply.score * adjust
			# score = post_class_score_top5[plabel] * reply.score
			if key in reply_score: score = max(score, reply_score[key])
			reply_score[key] = score
			verse = reply.verse
			comment = reply.comment
			content = {
				'verse_url': verse.url, 
				'verse_body': verse.body, 
				'introduction': comment.introduction,
				'postscript': comment.postscript
			}
			if not key in reply_content: reply_content[key] = content
			fractal += 1

	for emotion in emotion_score:
		emotionInst = Emotion.objects.get(title=emotion)
		sub = VerseEmotionMap.objects.filter(emotion=emotionInst).order_by('pk')
		for reply in sub:
			adjust = (1000 + fractal) / 1000
			key = (reply.verse.pk, reply.comment.pk)
			score = emotion_score[emotion] * reply.score * adjust
			# score = emotion_score[emotion] * reply.score
			if key in reply_score: score = max(score, reply_score[key])
			reply_score[key] = score
			verse = reply.verse
			comment = reply.comment
			content = {
				'verse_url': verse.url, 
				'verse_body': verse.body, 
				'introduction': comment.introduction,
				'postscript': comment.postscript
			}
			if not key in reply_content: reply_content[key] = content
			fractal += 1

	reply_ordered = {}
	rid = 0
	print('-- DEBUG --')
	for k in reversed(sorted(reply_score, key=lambda k:reply_score[k])):
		print(reply_score[k])
		print(reply_content[k])
		reply_ordered[rid] = reply_content[k]
		rid = rid + 1
		if rid >= 10: break

	# for k in sorted(reply_ordered.keys(), key=int): 
	# 	print(reply_ordered[k])
	return reply_ordered


class WEB(TemplateView):
	def get_context_data(self, **kwargs):
		context = super(WEB, self).get_context_data(**kwargs)
		context['focused_verses'] = self.kwargs['focused_verses']
		self.template_name ='knowledge_base/WEB/newHTMLs/' + self.kwargs['book_chapter'] + '.html'
		return context	

class Overview(TemplateView):
	template_name='knowledge_base/overview.html'
	title = 'Overview'


class SentenceLabels(TemplateView):
	template_name='knowledge_base/sentence_labels.html'
	title = 'Sentence Labels'

	slabels = SentenceLabel.objects.all()
	for slabel in slabels:
		slabel.positives = SentenceMembership.objects.filter(label=slabel).count()
		slabel.supervisors = SentenceMembership.objects.filter(label=slabel, supervise=False).count()
		slabel.save()

	@cached_property
	def sentence_labels(self): return SentenceLabel.objects.all().order_by('title')


class PostLabels(TemplateView):
	template_name='knowledge_base/post_labels.html'
	title = 'Post Labels'

	plabels = PostLabel.objects.all()
	for plabel in plabels:
		plabel.positives = PostMembership.objects.filter(label=plabel).count()
		plabel.save()

	@cached_property
	def post_labels(self): return PostLabel.objects.all().order_by('title')


class AnswerRules(TemplateView):
	template_name='knowledge_base/answer_rules.html'
	title = 'Anser Rules'


class SentenceLabeling(DetailView):

knowledge_base/templates/knowledge_base/answer_rules.html
{% extends 'knowledge_base/base.html' %}


{% block content %}



{% endblock %}

knowledge_base/templates/knowledge_base/base-home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}BibleBot{% endblock %}</title>
	{% load staticfiles %}
	<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy|Capriola' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'knowledge_base/style.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'knowledge_base/base-home.css' %}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'knowledge_base/ladda-themeless.min.css' %}">
    <script src="{% static 'knowledge_base/js/spin.min.js' %}"></script>
    <script src="{% static 'knowledge_base/js/ladda.min.js' %}"></script>

	
	<!-- (Optional) Latest compiled and minified JavaScript translation files -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/i18n/defaults-*.min.js"></script>

	<script src="{% static 'knowledge_base/js/home.js' %}"></script>
</head>
<body>
    <img id="background" src="{% static 'knowledge_base/images/bible-photo.jpg' %}">
    <div class="layerTransparent"></div>
	<div class="container">
		<div class="main">
            <h2 class="page-header">
                <a class="navbar-brand" href="{% url 'knowledge_base:home' %}">BibleBot</a>
                <span class="john836">if the Son sets you free, you will be free indeed. (John 8:36)</span>
            </h2>
			{% block content %}{% endblock %}
		</div> 
	</div>
</body>
</html>

knowledge_base/templates/knowledge_base/base-web.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}BibleBot{% endblock %}</title>
	{% load staticfiles %}
	<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy|Capriola|Roboto' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'knowledge_base/style.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'knowledge_base/css/base-web.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
</head>
<body>
    <div class="layerTransparent"></div>
	<div class="container">
		<div class="main">
            <h2 class="page-header">
                <a class="navbar-brand" href="{% url 'knowledge_base:home' %}">BibleBot</a>
                <span class="john836">if the Son sets you free, you will be free indeed. (John 8:36)</span>
            </h2>
			{% block content %}{% endblock %}
		</div> 
	</div>
</body>


<script>

$(document).ready(function() {
    var separate_varses = [];
    var focused_verses = "{{ focused_verses }}";
    var m  = focused_verses.match(/^(\d+)-(\d+)$/);
    if (m) {
        var start = parseInt(m[1]);
        var end = parseInt(m[2]);
        for (var verse = start; verse <= end; verse++) separate_varses.push(verse);

    } else {
        separate_varses.push(focused_verses);
    }
    // alert(separate_varses);
    for (var i=0; i < separate_varses.length; i++ ){
        $('.V' + separate_varses[i] + '_NoBody').css('border-bottom', 'solid 2px rgb(121, 167, 243)');
    }

});

</script>

</html>

knowledge_base/templates/knowledge_base/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}BibleBot - {{ view.title}}{% endblock %}</title>
	{% load staticfiles %}
	<link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<link href='https://fonts.googleapis.com/css?family=Satisfy|Capriola' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'knowledge_base/style.css' %}"/>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js"></script>

	<!-- (Optional) Latest compiled and minified JavaScript translation files -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/i18n/defaults-*.min.js"></script>

	<script src="{% static 'knowledge_base/js/main.js' %}"></script>
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-sm-3 col-md-2 sidebar">

                <div style="margin-bottom: 70px;">
                    <a href="" class="navbar-brand">BibleBot</a>
                </div>

                <div style="clear:both; background-color:rgb(248, 248, 252)">
        			<ul class="nav nav-sidebar">
                        <li><a href="{% url 'knowledge_base:home' %}">Home</a></li>
                        <li><a href="{% url 'knowledge_base:overview' %}">Overview</a></li>
        				<li><a href="{% url 'knowledge_base:PostLabels' %}">Post Labels</a></li>
        				<li><a href="{% url 'knowledge_base:SentenceLabels' %}">Sentence Labels</a></li>
        				<li><a href="{% url 'knowledge_base:AnswerRules' %}">Answer Rules</a></li>
        			</ul>
                </div>
			</div>
			<div class="col-sm-9 col-md-10 main">
                <h2 class="page-header">{{ view.title}}</h2>
				{% block content %}{% endblock %}
			</div> 
		</div>	   
	</div>
</body>
</html>

knowledge_base/templates/knowledge_base/labels.html
{% extends 'knowledge_base/base.html' %}


{% block title %}labels{% endblock %}
{% block content %}

<div class="row">
<div class="col-sm-6">
	<h3>{{ view.post_title}}</h3>
	<ul style="list-style:none;">
	  {% for label in view.post_labels %}
	  	{% if label.positives > 0 %}
	  		ARUYO
	  	{% else %}
	    	<li>{{ label }}</li>
	    {% endif %}
	  {% endfor %}
	<ul>
</div>

<div class="col-sm-6">
<h3>{{ view.sentence_title}}</h3>
	<ul style="list-style:none;">
	  {% for label in view.sentence_labels %}
	  	{% if label.positives > 0 %}
	  		<li><a href="{% url 'knowledge_base:SentenceLabeling' label.id %}">{{ label }}</a></li>
	  	{% else %}
	    	<li>{{ label }}</li>
	    {% endif %}
	  {% endfor %}
	<ul>
</div>
{% endblock %}

knowledge_base/templates/knowledge_base/overview.html
{% extends 'knowledge_base/base.html' %}


{% block content %}



{% endblock %}

knowledge_base/templates/knowledge_base/sentence_labels.html
{% extends 'knowledge_base/base.html' %}


{% block content %}


<btn class="btn btn-primary svm_learn_sentences">SVM Learn</btn>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Label</th>
      <th>Positives</th>
      <th>Supervisors</th>
      <th>Precision</th>
      <th>Recall</th>
    </tr>
  </thead>
  <tbody>
	  {% for label in view.sentence_labels %}
	  <tr>
	  	<td>
	  	{% if label.title == 'MULTI_EMOTIONS' or label.title == 'NOT_EMOTION' or label.title == 'UNKNOWN_EMOTION' %}
	    	{{ label }}
	  	{% elif label.positives > 0 %}
	  		<a href="{% url 'knowledge_base:SentenceLabeling' label.id %}">{{ label }}</a></li>
	  	{% else %}
	    	{{ label }}
	    {% endif %}
	    </td>
	    <td>{{ label.positives }}</td>
	    <td>{{ label.supervisors }}</td>
	    <td>{{ label.precision }}</td>
	    <td>{{ label.recall }}</td>

	  {% endfor %}  
	  </tr>
  </tbody>


{% endblock %}